import Head from 'next/head';
import Discription from '../components/Discription';
import Feed from '../components/Feed';
import Slider from '../components/Slider';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>NETX | Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center flex-col">
        <Hero />
        <Slider />
        <Discription />
        {/* <Feed /> */}
      </div>
    </div>
  );
}
