import Head from "next/head";
import Discription from "../components/Discription";
import Feed from "../components/Feed";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center flex-col ">
        <div className="flex justify-center items-center flex-col lg:flex-row">
          <Slider />
          <Feed />
        </div>
        <Discription />
      </div>
    </div>
  );
}
