import Head from "next/head";
import Person from "../components/Person";
export default function Home() {
  const data = [
    {
      name: "Praveen Chandrahas",
      designation: "PhD",
      i_link: "",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Harish,",
      designation: "PhD",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538214/ecell/NetX/Harish_wgncdg.jpg",
      p_link: "https://www.harishsa.com",
      l_link: "",
      info: " ",
    },
    {
      name: "K. Shiv Kumar",
      designation: "PhD",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538212/ecell/NetX/Shiv_brmw0v.jpg",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Ranjitha K",
      designation: "PhD",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538205/ecell/NetX/Ranjitha_K_o7tjfy.png",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Sanyan Dey",
      designation: "Mtech (RA)",
      i_link: "",
      p_link: "",
      l_link: "",
      info: "jointly with Dr. Ramakrishna",
    },
    {
      name: "Divya Pathak",
      designation: "Mtech (RA)",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538212/ecell/NetX/IMG_20221005_125118_u6p6n5.jpg",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Prem Kumar Saraf",
      designation: "MTech (TA)",
      i_link: "",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Sankalp Mittal",
      designation: "MTech (RA)",
      i_link: "",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Animesh Singh",
      designation: "MTech (RA)",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538206/ecell/NetX/Animesh_jmwxnt.jpg",
      p_link: "",
      l_link: "",
      info: " ",
    },
    {
      name: "Ankit Sharma",
      designation: "MTech (RA)",
      i_link:
        "https://res.cloudinary.com/dbmw0xoar/image/upload/v1666538213/ecell/NetX/Ankit_eegv1c.jpg",
      p_link: "",
      l_link: "",
      info: " ",
    },
  ];
  return (
    <div>
      <Head>
        <title>People: NETX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-center text-2xl lg:text-3xl p-5">Our group</h2>
      <div className="grid md:grid-cols-3 lg:grid-cols-4 gap-0 ">
        {data.map((item) => (
          <Person
            name={item.name}
            designation={item.designation}
            i_link={item.i_link}
            p_link={item.p_link}
            info={item.info}
            key={item.name}
          />
        ))}
      </div>
    </div>
  );
}
